# Strategy Configuration
# CAD-IG Trading Strategy - Weekly Rebalancing

strategy:
  name: "weekly_ensemble_strategy"
  type: "weekly"
  description: "Weekly rebalancing strategy using ML ensemble"
  rebalance_frequency: "W-FRI"  # Weekly on Friday
  
  # Model ensemble configuration
  models:
    - name: "lightgbm_primary"
      type: "lightgbm"
      weight: 0.30
      params:
        n_estimators: 200
        max_depth: 5
        learning_rate: 0.02
        num_leaves: 20
        min_child_samples: 40
        subsample: 0.7
        colsample_bytree: 0.7
        reg_alpha: 0.2
        reg_lambda: 0.2
        random_state: 42
    
    - name: "xgboost_secondary"
      type: "xgboost"
      weight: 0.25
      params:
        n_estimators: 200
        max_depth: 6
        learning_rate: 0.02
        subsample: 0.7
        colsample_bytree: 0.7
        reg_alpha: 0.1
        reg_lambda: 0.1
        random_state: 43
    
    - name: "random_forest"
      type: "random_forest"
      weight: 0.25
      params:
        n_estimators: 300
        max_depth: 10
        min_samples_split: 40
        min_samples_leaf: 20
        random_state: 44
    
    - name: "lightgbm_aggressive"
      type: "lightgbm"
      weight: 0.20
      params:
        n_estimators: 150
        max_depth: 6
        learning_rate: 0.03
        num_leaves: 30
        min_child_samples: 30
        subsample: 0.8
        colsample_bytree: 0.8
        reg_alpha: 0.1
        reg_lambda: 0.1
        random_state: 45
  
  # Signal generation
  signal_generation:
    method: "probability_threshold"
    threshold: 0.48
    threshold_type: "fixed"  # Options: fixed, adaptive, regime_based
    min_probability: 0.30
    max_probability: 0.70
    
    # Adaptive threshold settings (if threshold_type: adaptive)
    adaptive:
      enabled: false
      volatility_scaling: true
      regime_adjustment: true
    
    # Signal filters
    filters:
      - type: "momentum"
        enabled: false
        min_momentum: 0.0
      - type: "volatility"
        enabled: false
        max_volatility: 0.05
  
  # Feature selection
  features:
    selection_method: "mutual_info"
    n_features: 60
    feature_groups:
      - momentum
      - spreads
      - macro
      - regime
      - statistical
      - interactions
  
  # Training configuration
  training:
    train_test_split: 0.5
    validation_method: "walk_forward"
    retraining_frequency: 252  # Trading days (annual)
    min_training_samples: 500
    
    # Walk-forward settings
    walk_forward:
      enabled: true
      initial_train_size: 0.5
      step_size: 252  # Retrain annually
  
  # Risk management
  risk:
    max_position_size: 1.0  # 100% long or 0% (binary)
    max_drawdown_limit: 0.05  # 5% max drawdown trigger
    stop_loss: null  # Not used for long-only
    take_profit: null  # Not used for long-only
    
    # Position sizing (future enhancement)
    position_sizing:
      method: "binary"  # Options: binary, kelly, fixed_fractional
      kelly_fraction: 1.0
  
  # Performance targets
  targets:
    min_annualized_return: 0.04  # 4%
    min_sharpe_ratio: 2.0
    max_drawdown: -0.02  # -2%
    min_win_rate: 0.75  # 75%

# Data configuration
data:
  source: "csv"
  path: "data/raw/with_er_daily.csv"
  date_column: "Date"
  target_column: "cad_ig_er_index"
  
  # Data validation
  validation:
    check_missing: true
    check_outliers: true
    max_missing_pct: 0.05
    outlier_std: 5.0
  
  # Preprocessing
  preprocessing:
    handle_missing: "forward_fill"
    remove_outliers: false
    normalize_dates: true

# Backtesting configuration
backtest:
  start_date: null  # null = use all available data
  end_date: null
  initial_capital: 100.0  # Base 100
  
  # Transaction costs
  costs:
    commission: 0.0010  # 10 bps per trade
    slippage: 0.0005  # 5 bps slippage
  
  # Reporting
  reporting:
    generate_trade_blotter: true
    generate_plots: true
    save_results: true
    output_dir: "results/backtests"
  
  # Validation tests
  validation:
    run_bias_tests: true
    tests:
      - lookahead_bias
      - overfitting
      - out_of_time
      - parameter_sensitivity
      - transaction_costs

# Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/strategy.log"
  console: true

